swagger: "2.0"

info:
  title: "Online Food Ordering System"
  version: "1.0"

basePath: /v1.0

paths:
  /restaurants/:
    get:
      responses:
        '200':
          description: 'Fetch a list of restaurants'
          schema:
            type: array
            items:
              $ref: '#/definitions/Restaurants'
        '400':
          description: 'Oops wrong place!!'
          schema:
            type: array
            items:
              $ref: '#/definitions/Restaurants'
        '500':
          description: 'Sorry it isnt you its me'
          schema:
            type: array
            items:
              $ref: '#/definitions/Restaurants'
definitions:
  Restaurants:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name: { type: string }
